# Generated by Django 4.2 on 2023-04-15 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_games', '0001_initial'),
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_scored', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_challenges', to='challenges.challenge')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_challenges', to='user_games.user_game')),
            ],
            options={
                'unique_together': {('game', 'challenge')},
            },
        ),
    ]
