# Generated by Django 4.2 on 2023-04-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_challenge',
            name='revealed_squares',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_challenge',
            name='total_available_points',
            field=models.IntegerField(default=1200),
        ),
    ]
