# Generated by Django 4.2 on 2023-04-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_game',
            name='seed',
            field=models.IntegerField(default=0),
        ),
    ]
