# Generated by Django 4.2 on 2023-04-15 13:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenge_difficulties', '0001_initial'),
        ('challenge_themes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(max_length=100)),
                ('hint', models.CharField(max_length=100)),
                ('image_url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='challenge_difficulties.challenge_difficulty')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='challenge_themes.challenge_theme')),
            ],
        ),
    ]
